MedOR/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedOR.Common;

namespace MedOR.Controllers
{
    [Authorize]
    public class PatientController : Controller
    {
        //
        // GET: /Patient/

        #region Constructor
        private DataServices.Service _MedOrSvc;

        public PatientController()
        {
            _MedOrSvc = new DataServices.Service();
        }
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        [Comm.AuthorizeUser(AccessLevel = "View Patients")]
        public ActionResult ListOfPatients()
        {
            var patients = _MedOrSvc.GetAllPatients(new Guid(HttpContext.User.Identity.Name));
            return View(patients);
        }

        [Comm.AuthorizeUser(AccessLevel = "Create Patients")]
        public ActionResult CreateNewPatient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateNewPatient(DataModel.PaitentModel model, HttpPostedFileBase uploadFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    model.Image = new byte[uploadFile.ContentLength];
                    uploadFile.InputStream.Read(model.Image, 0, uploadFile.ContentLength);
                }

                model.CreatedBy = new Guid(HttpContext.User.Identity.Name);
                model.CreatedOn = DateTime.Now;
                model.DateOfBirth = new DateTime(Convert.ToInt32(model.YYYY), Convert.ToInt32(model.MM), Convert.ToInt32(model.DD));

                var newUser = _MedOrSvc.AddNewPatient(model);

                if (newUser != 0)
                    return Redirect("/Patient/ListOfPatients");
            }
            return View(model);
        }

        public ActionResult ShowPatientImage(Guid id)
        {
            var image = _MedOrSvc.GetPatientImage(new Guid(id.ToString()));
            return File(image, "image/jpg");
        }

        [Comm.AuthorizeUser(AccessLevel = "Edit Patients")]
        public ActionResult EditPatient(Guid? id)
        {
            if (String.IsNullOrEmpty(id.ToString()) || id == Guid.Empty)
                id = new Guid(HttpContext.User.Identity.Name);
            var model = _MedOrSvc.GetPatientByID(id.Value);
            model.DD = model.DateOfBirth.Day.ToString();
            model.MM = model.DateOfBirth.Month.ToString();
            model.YYYY = model.DateOfBirth.Year.ToString();

            if (model == null)
            {
                //return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult EditPatient(DataModel.PaitentModel model, HttpPostedFileBase uploadFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadFile != null && uploadFile.ContentLength > 0)
                {
                    model.Image = new byte[uploadFile.ContentLength];
                    uploadFile.InputStream.Read(model.Image, 0, uploadFile.ContentLength);
                }

                model.ModifiedBy = new Guid(HttpContext.User.Identity.Name);
                model.ModifiedOn = DateTime.Now;
                model.DateOfBirth = new DateTime(Convert.ToInt32(model.YYYY), Convert.ToInt32(model.MM), Convert.ToInt32(model.DD));
                var editPatient = _MedOrSvc.UpdatePatient(model);

                if (editPatient != 0)
                    return Redirect("/Patient/ListOfPatients");
            }
            return View(model);
        }

        [Comm.AuthorizeUser(AccessLevel = "Delete Patients")]
        public ActionResult DeletePatient(Guid id)
        {
            var deleted = _MedOrSvc.DeletePatientByID(id);
            if (deleted != 0)
                return Redirect("/Patient/ListOfPatients");
            return View();
        }

        public ActionResult PatientAccount(Guid PatientID)
        {
            var Accounts = _MedOrSvc.GetAllPendingPaymentForPatient(PatientID);


            return View(Accounts);
        }

    }
}

MedOR/Views/Patient/PatientAccount.cshtml
@{
    ViewBag.Title = "PatientAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DataModel.AccountingModel

@section CSS{
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/select2/select2.css" />
    <link rel="stylesheet" href="~/Content/assets/plugins/DataTables/media/css/DT_bootstrap.css" />
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Account</title>
</head>
<body>


    @*<div class="modal fade" id="panel-remove1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Remove
                </h4>
            </div>
            <div id="modalbody1" class="modal-body">


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    Cancel
                </button>
                <button type="button" onclick="return execRemove1()" class="btn btn-primary">
                    OK
                </button>
            </div>
        </div>*@
    <!-- /.modal-content -->
    <!-- /.modal-dialog -->
    @*</div>*@


    <div class="row">
        <div class="col-sm-12">
            <!-- start: PAGE TITLE & BREADCRUMB -->
            <ol class="breadcrumb">
                <li><i class="clip-file"></i><a href="#">Patients </a></li>
                <li class="active">List Of Patients </li>
            </ol>
            <div class="page-header">
                <h1>
                    Patient's Account <small>@Model.PFullName</small>
                </h1>
            </div>
            <!-- end: PAGE TITLE & BREADCRUMB -->
        </div>
    </div>
    <!-- end: PAGE HEADER -->

    <div class="row">
        <div class="col-md-12">
            <!-- start: DYNAMIC TABLE PANEL -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>Accounts Patients
                    <div class="panel-tools">
                        <a class="btn btn-xs btn-link panel-collapse collapses" href="#"></a>
                        @*<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal"> <i class="fa fa-wrench"></i></a>*@
                        <a class="btn btn-xs btn-link panel-refresh" href="@Url.Action("ListOfPatients", "Patient")"><i class="fa fa-refresh"></i></a>
                        <a class="btn btn-xs btn-link panel-expand" href="#"> <i class="fa fa-resize-full"></i></a>
                    </div>
                </div>
                <div class="panel-body">

                    @*<div class="row">

                        <div class='col-md-3'>
                            <div class='form-group'>
                                <label class='control-label' for='form-field-select-1'>
                                    Doctor <span class="symbol required"></span>
                                </label>
                                @Html.DropDownListFor(m => m.SelectedDoctorID, MedOR.Common.Comm.GetDoctorList(@Model.DoctorModels), "--Select user's Doctor--", new { @class = "form-control", id = "SelectedDoctorIDs", Name = "SelectedDoctorIDs" })
                            </div>
                        </div>
                  
                    </div>*@




                    <table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">

                        <thead>
                            <tr>
                                <th>
                                    Date
                                </th>
                               
                                <th>
                                    Consultation Title
                                </th>
                                <th>
                                    Fee
                                </th>
                                <th>
                                    Paid
                                </th>
                            </tr>
                        </thead>
                        @{
                            foreach (var account in @Model.AccountingModels.ToList())
                            {
                                <tbody>
                                    <tr id="@account.ConsultationID">
                                        <td class="hidden-xs">
                                            @account.CCreatedOn
                                        </td>
                                        
                                        <td>
                                            @account.Ctitle
                                        </td>
                                        <td>
                                            @account.CFees.ToString("0.00")  @account.Ccurrency
                                        </td>
                                        <td class="center">
                                            No &nbsp;
                                            <a href="#panel-remove1" class="btn btn-xs btn-bricky tooltips" data-placement="top"
                                               data-original-title="PAY Consultation" data-toggle="modal">
                                                <i class="fa fa-money fa fa-white">
                                                    Yes
                                                </i>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            }
                        }
                    </table>

                </div>
            </div>
            <!-- end: DYNAMIC TABLE PANEL -->
        </div>
    </div>
</body>
</html>

@section Scripts{

    <script type="text/javascript" src="~/Content/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
    <script type="text/javascript" src="~/Content/assets/js/table-data.js"></script>
    <script type="text/javascript">
    jQuery(document).ready(function ()
    {
        @*TableData.init();*@
     $("#sample_1").DataTable();
            //$("#sample_11").DataTable();
    });


        $("#sample_1 tr").click(function () {
            debugger;
            var IdRow = $(this).attr('id');
            window.location = '/Accounting/AccountPaid?&ConsultationID=' + IdRow;
            //name = $(this).attr('name');
            //Val = $(this).attr('value');
            //IdRow = $(this).attr('id');
            //document.getElementById('modalbody1').innerHTML = 'Are you sure you want to remove ?';
        });
        //function execRemove1() {
        //    window.location = '/Accounting/Account?&DescriptionID=' + IdRow;
        //    return false;
        //}

    </script>
}